In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('/content/bert_hateeval.csv')
df2=pd.read_csv('/content/tfidf_ml_hateeval.csv')

In [3]:
df_eval_hateeval_ml=pd.merge(df1, df2, how="inner")

In [5]:
rslt_df = df_eval_hateeval_ml[(df_eval_hateeval_ml['hateeval_nb'] > 0.6) |
          (df_eval_hateeval_ml['hateeval_lg']>0.6)| (df_eval_hateeval_ml['hateeval_gb']>0.6) | (df_eval_hateeval_ml['hateeval_svc']>0.6) | (df_eval_hateeval_ml['hateeval_bert']>0.6) ]

In [6]:
rslt_df

       Unnamed: 0                       _id  ... hateeval_gb  hateeval_svc
24             33  61e12fe00776fd1c94712a0c  ...    0.434715      0.445179
32             45  61c1e18e78e60889d95c6dd7  ...    0.701160      0.925811
40             58  61e11c6e6a2d2dcce881165d  ...    0.414627      0.479221
62             88  61e1378029158668d17a99c7  ...    0.506817      0.457212
82            115  61e41ee2e89da792d13b1d1c  ...    0.454548      0.558289
...           ...                       ...  ...         ...           ...
69130      114592  61dfe6c5e7dfd99c9f9fa163  ...    0.609987      0.846656
69144      114616  61d590ed7b77dfb5f2880f8f  ...    0.428334      0.408341
69150      114623  61e10e2b85ff1e72f7415c38  ...    0.408327      0.382343
69161      114636  61cbf22d16418412f84e7fbb  ...    0.381266      0.303768
69166      114645  61e13ba6d27c0a6f757ed08e  ...    0.408327      0.467724

[6682 rows x 8 columns]